GET https://gispsy.amorce.org/api/produits
Accept: application/json
Content-Type: application/json

###

GET https://gispsy.amorce.org/api/produits/1
Accept: application/json
Content-Type: application/json


###

POST https://gispsy.amorce.org/api/produits/1
Accept: application/json
Content-Type: application/json

{
  "nom": "string",
  "quantiter": 0,
  "description": "string",
  "prixPHUT": "5",
  "fournisseur":"/api/fournisseurs/1",
  "updateAt": "2023-07-05T14:41:13.859Z"

}